[workspace]
resolver = "2"
members = [
    "packages/ui",
    "packages/desktop",
    "packages/mobile",
]

[workspace.dependencies]
dioxus = { version = "0.7.0" }

# workspace
ui = { path = "packages/ui" }

