[application]
name = "rustyvpn"
version = "0.1.0"

[android]
package_name = "com.orionexx.rustyvpn"
permissions = [
    "android.permission.ACCESS_NETWORK_STATE",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.WAKE_LOCK",
    "android.permission.FOREGROUND_SERVICE_CONNECTED_DEVICE"
]

[bundle]
identifier = "com.orionexx.rustyvpn"
name = "rustyvpn"
publisher = "Orionexx"
version = "0.1.0"