[application]
name = "rustyvpn"
version = "0.1.0"

[android]
package_name = "com.orionexx.rustyvpn"
permissions = [
    "android.permission.READ_CONTACTS",
]

[bundle]
identifier = "com.orionexx.rustyvpn"
name = "rustyvpn"
publisher = "Orionexx"
version = "0.1.0"