[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-util = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
ssh = { workspace = true }
proxy = { workspace = true }
socks = { workspace = true }
openssl = { workspace = true }
ndk-context = "0.1.1"
jni = { workspace =  true }

